//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transprensa.Intranet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capacitaciones
    {
        public int idCapacitacion { get; set; }
        public string resumen { get; set; }
        public int idArea { get; set; }
        public string enlace { get; set; }
        public string nombre { get; set; }
    
        public virtual Areas Areas { get; set; }
    }
}
