//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transprensa.Intranet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int idEvento { get; set; }
        public int dia { get; set; }
        public int mes { get; set; }
        public string nombre { get; set; }
        public int idTipoEvento { get; set; }
        public Nullable<int> ano { get; set; }
    
        public virtual TipoEvento TipoEvento { get; set; }
    }
}
