//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transprensa.Intranet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagenes
    {
        public int idImagen { get; set; }
        public int idNoticia { get; set; }
        public string nombre { get; set; }
        public string url { get; set; }
    
        public virtual Noticias Noticias { get; set; }
    }
}
